import { PendingTaskItem } from '@/shared/types/task';

export const Posts: PendingTaskItem[] = [
  {
    title: "국어 수행평가",
    dueDate: "2025-07-21",
    body: "5차시 국어 수행평가 해야겠죠?",
    link: "/submit/korean",
    available: false,
  },
  {
    title: "수학 수행평가",
    dueDate: "2025-07-22",
    body: "수학 과제 제출 잊지 마세요.",
    link: "/submit/math",
    available: false,
  },
  {
    title: "영어 독후감",
    dueDate: "2025-07-23",
    body: "지정 도서 독후감 제출.",
    link: "/submit/english",
    available: false,
  },
  {
    title: "과학 탐구 보고서",
    dueDate: "2025-07-24",
    body: "탐구 실험 결과 보고서 작성.",
    link: "/submit/science",
    available: false,
  },
  {
    title: "역사 발표 자료",
    dueDate: "2025-07-25",
    body: "역사 발표 자료 제출 마감입니다.",
    link: "/submit/history",
    available: false,
  },
  {
    title: "기술 가정 실습일지",
    dueDate: "2025-07-26",
    body: "실습 내용 기록 제출 필수!",
    link: "/submit/tech",
    available: false,
  },
  {
    title: "미술 감상문",
    dueDate: "2025-07-27",
    body: "작품 감상문 A4 1장 제출.",
    link: "/submit/art",
    available: false,
  },
  {
    title: "체육 건강기록표",
    dueDate: "2025-07-28",
    body: "건강기록표 작성 및 업로드.",
    link: "/submit/pe",
    available: false,
  },
  {
    title: "음악 감상일지",
    dueDate: "2025-07-29",
    body: "클래식 감상 후 소감 작성.",
    link: "/submit/music",
    available: false,
  },
  {
    title: "정보 코딩 과제",
    dueDate: "2025-07-30",
    body: "코딩 과제 깃헙에 업로드.",
    link: "/submit/coding",
    available: false,
  },
  {
    title: "도덕 토론 자료",
    dueDate: "2025-08-01",
    body: "도덕 시간에 사용할 토론 자료.",
    link: "/submit/ethics",
    available: false,
  },
  {
    title: "생활과 윤리 발표문",
    dueDate: "2025-08-02",
    body: "윤리 관련 주제 발표문 제출.",
    link: "/submit/lifeethics",
    available: false,
  },
  {
    title: "사회 문제 분석",
    dueDate: "2025-08-03",
    body: "최근 사회 이슈 분석 리포트.",
    link: "/submit/society",
    available: false,
  },
  {
    title: "진로 계획서",
    dueDate: "2025-08-04",
    body: "미래 직업 관련 진로 계획 작성.",
    link: "/submit/career",
    available: false,
  },
  {
    title: "한문 독해 과제",
    dueDate: "2025-08-05",
    body: "한문 문장 해석 및 해설 작성.",
    link: "/submit/chinese",
    available: false,
  },
  {
    title: "경제 보고서",
    dueDate: "2025-08-06",
    body: "경제 이슈에 대한 보고서 제출.",
    link: "/submit/economy",
    available: false,
  },
  {
    title: "지리 필기 숙제",
    dueDate: "2025-08-07",
    body: "지리 교과서 필기 정리 제출.",
    link: "/submit/geography",
    available: false,
  },
  {
    title: "문학 감상문",
    dueDate: "2025-08-08",
    body: "현대 문학 작품 감상문 제출.",
    link: "/submit/literature",
    available: false,
  },
  {
    title: "생명과학 실험 결과",
    dueDate: "2025-08-09",
    body: "실험 결과 분석표 제출하세요.",
    link: "/submit/bio",
    available: false,
  },
  {
    title: "지구과학 과제",
    dueDate: "2025-08-10",
    body: "화산과 지진 관련 보고서 작성.",
    link: "/submit/earthscience",
    available: false,
  },
];